language: node_js

node_js:
  - "7"

install:
  - yarn install

script:
  - yarn eslint
  - yarn test

cache:
  directories:
    - node_modules

branches:
  only:
    - master

env:
  - CXX=g++-4.8
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8